# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
set -U background '#282c34'
set -U foreground '#abb2bf'
set -U cursor '#abb2bf'
set -U color0 '#282c34'
set -U color1 '#e06c75'
set -U color2 '#98c379'
set -U color3 '#e5c07b'
set -U color4 '#61afef'
set -U color5 '#c678dd'
set -U color6 '#56b6c2'
set -U color7 '#abb2bf'
set -U color8 '#5c6370'
set -U color9 '#e06c75'
set -U color10 '#98c379'
set -U color11 '#e5c07b'
set -U color12 '#61afef'
set -U color13 '#c678dd'
set -U color14 '#56b6c2'
set -U color15 '#c8ccd4'

set -U fish_color_normal normal
set -U fish_color_command green
set -U fish_color_param cyan
set -U fish_pager_color_completion
set -U fish_pager_color_description $fish_color_quote yellow
set -U fish_pager_color_progress brwhite --background=cyan
set -U fish_color_history_current --bold
