# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
set -l color00 '#1f2329'
set -l color01 '#e06c75'
set -l color02 '#98c379'
set -l color03 '#e5c07b'
set -l color04 '#61afef'
set -l color05 '#c678dd'
set -l color06 '#56b6c2'
set -l color07 '#c0c9d4'
set -l color08 '#6a7485'
set -l color09 '#e06c75'
set -l color0A '#98c379'
set -l color0B '#e5c07b'
set -l color0C '#61afef'
set -l color0D '#c678dd'
set -l color0E '#56b6c2'
set -l color0F '#c8ccd4'

set -l FZF_NON_COLOR_OPTS

for arg in (echo $FZF_DEFAULT_OPTS | tr " " "\n")
    if not string match -q -- "--color*" $arg
        set -a FZF_NON_COLOR_OPTS $arg
    end
end

set -Ux FZF_DEFAULT_OPTS "$FZF_NON_COLOR_OPTS"" --color=bg+:$color00,bg:$color00,spinner:$color0E,hl:$color0D"" --color=fg:$color07,header:$color0D,info:$color0A,pointer:$color0E"" --color=marker:$color0E,fg+:$color06,prompt:$color0A,hl+:$color0D"
