-- AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
return {
  {
    "olimorris/onedarkpro.nvim",
    priority = 1000,
    config = function()
      require("onedarkpro").setup({
        theme = "onedark",
        highlights = {
          LineNr = { fg = "#6a7485", bg = "bg" },
          TabLineFill = { bg = "bg" },
          TabLine = { bg = "bg" },
          TabLineSel = { bg = "#1f2329" },
        },
      })
      vim.cmd("colorscheme onedark")
    end,
  },
}
