#!/usr/bin/env bash
# Single source of truth for this theme.

THEME_NAME="One Dark Pro Flat"

BACKGROUND="#282c34"
SURFACE="#21252b"
OVERLAY="#2c313a"
SELECTION="#3e4451"
FOREGROUND="#abb2bf"
COMMENT="#5c6370"
SUBTLE="#9aa2ad"
BORDER_SOFT="#5c6370"

RED="#e06c75"
GREEN="#98c379"
YELLOW="#e5c07b"
BLUE="#61afef"
MAGENTA="#c678dd"
CYAN="#56b6c2"
ORANGE="#d19a66"

BRIGHT_RED="#be5046"
BRIGHT_GREEN="#7da869"
BRIGHT_YELLOW="#d19a66"
BRIGHT_BLUE="#528bff"
BRIGHT_MAGENTA="#d070ff"
BRIGHT_CYAN="#4aa5b7"
BRIGHT_WHITE="#c8ccd4"

# Fully solid windows everywhere.
WINDOW_OPACITY="1.0"
TERMINAL_BACKGROUND_OPACITY="1.0"
TERMINAL_SELECTION_BACKGROUND="#4f6080"
TERMINAL_SELECTION_FOREGROUND="#f2f6ff"

# Walker geometry (balanced density, no wrapper padding around search input)
WALKER_RADIUS="6"
WALKER_SEARCH_PADDING_Y="0"
WALKER_SEARCH_PADDING_X="0"
WALKER_WRAPPER_PADDING_Y="0"
WALKER_WRAPPER_PADDING_X="0"
WALKER_INPUT_PADDING_Y="8"
WALKER_INPUT_PADDING_X="12"

# Waybar compact sizing
WAYBAR_HEIGHT_PX="22"
WAYBAR_FONT_SIZE_PT="9"
WAYBAR_THEME_FONT_SIZE_PX="9"
WAYBAR_MODULE_MIN_WIDTH="0"
WAYBAR_MODULE_MARGIN="0 1px"
WAYBAR_MODULE_PADDING="0 4px"
WAYBAR_WORKSPACE_PADDING="0 0"
WAYBAR_WORKSPACE_MARGIN="0 1px 0 0"
WAYBAR_SYSTEM_ICON_SIZE_PX="12"
WAYBAR_RESOURCE_ICON_SIZE_PX="11"
WAYBAR_RIGHT_ICON_MIN_WIDTH_PX="24"
WAYBAR_ITEM_RADIUS_PX="2"
WAYBAR_HOVER_BG="${SELECTION}"
WAYBAR_CLOCK_FONT_SIZE_PX="11"
WAYBAR_WORKSPACE_FONT_SIZE_PX="11"
WAYBAR_OMARCHY_ICON_SIZE_PX="12"
WAYBAR_IDLE_ICON_SIZE_PX="12"

# Waybar semantic colors (high contrast, low saturation)
WAYBAR_NEUTRAL_BG="${SURFACE}"
WAYBAR_NEUTRAL_BG_ALT="${SURFACE}"
WAYBAR_NEUTRAL_TEXT="${FOREGROUND}"
WAYBAR_MUTED_TEXT="${SUBTLE}"
WAYBAR_ACCENT_COOL="${CYAN}"
WAYBAR_ACCENT_WARM="${YELLOW}"
WAYBAR_ACCENT_POWER="${GREEN}"
WAYBAR_ALERT_BG="${RED}"
WAYBAR_ALERT_TEXT="${BACKGROUND}"
