#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

# shellcheck source=../theme.tokens.sh
source "${ROOT_DIR}/theme.tokens.sh"

hex_nohash() {
  printf '%s' "${1#\#}"
}

hex_to_rgb() {
  local hex
  hex="$(hex_nohash "$1")"
  printf '%d, %d, %d' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

BACKGROUND_NOHASH="$(hex_nohash "${BACKGROUND}")"
SURFACE_NOHASH="$(hex_nohash "${SURFACE}")"
SELECTION_NOHASH="$(hex_nohash "${SELECTION}")"
FOREGROUND_NOHASH="$(hex_nohash "${FOREGROUND}")"
COMMENT_NOHASH="$(hex_nohash "${COMMENT}")"
RED_NOHASH="$(hex_nohash "${RED}")"
GREEN_NOHASH="$(hex_nohash "${GREEN}")"
YELLOW_NOHASH="$(hex_nohash "${YELLOW}")"
BLUE_NOHASH="$(hex_nohash "${BLUE}")"
MAGENTA_NOHASH="$(hex_nohash "${MAGENTA}")"
CYAN_NOHASH="$(hex_nohash "${CYAN}")"
ORANGE_NOHASH="$(hex_nohash "${ORANGE}")"
BRIGHT_WHITE_NOHASH="$(hex_nohash "${BRIGHT_WHITE}")"
BRIGHT_BLUE_NOHASH="$(hex_nohash "${BRIGHT_BLUE}")"
BRIGHT_MAGENTA_NOHASH="$(hex_nohash "${BRIGHT_MAGENTA}")"
BRIGHT_CYAN_NOHASH="$(hex_nohash "${BRIGHT_CYAN}")"

BLUE_RGB="$(hex_to_rgb "${BLUE}")"
BACKGROUND_RGB="$(hex_to_rgb "${BACKGROUND}")"
FOREGROUND_RGB="$(hex_to_rgb "${FOREGROUND}")"
SURFACE_RGB="$(hex_to_rgb "${SURFACE}")"
GREEN_RGB="$(hex_to_rgb "${GREEN}")"
YELLOW_RGB="$(hex_to_rgb "${YELLOW}")"
RED_RGB="$(hex_to_rgb "${RED}")"
SELECTION_RGB="$(hex_to_rgb "${SELECTION}")"
COMMENT_RGB="$(hex_to_rgb "${COMMENT}")"
BRIGHT_WHITE_RGB="$(hex_to_rgb "${BRIGHT_WHITE}")"

# Keep input and row content aligned even if older token names are used.
WALKER_ALIGNED_PADDING_X="${WALKER_ITEM_PADDING_X:-${WALKER_ITEM_PADDING_LEFT:-${WALKER_INPUT_PADDING_X:-12}}}"

cat > "${ROOT_DIR}/colors.toml" <<TOKENS
# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
accent = "${BLUE}"
cursor = "${FOREGROUND}"
foreground = "${FOREGROUND}"
background = "${BACKGROUND}"
selection_foreground = "${TERMINAL_SELECTION_FOREGROUND}"
selection_background = "${TERMINAL_SELECTION_BACKGROUND}"

color0 = "${TERMINAL_COLOR0}"
color1 = "${RED}"
color2 = "${GREEN}"
color3 = "${YELLOW}"
color4 = "${BLUE}"
color5 = "${MAGENTA}"
color6 = "${CYAN}"
color7 = "${FOREGROUND}"
color8 = "${TERMINAL_COLOR8}"
color9 = "${RED}"
color10 = "${GREEN}"
color11 = "${YELLOW}"
color12 = "${BLUE}"
color13 = "${MAGENTA}"
color14 = "${CYAN}"
color15 = "${BRIGHT_WHITE}"
TOKENS

cat > "${ROOT_DIR}/colors.fish" <<TOKENS
# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
set -U background '${BACKGROUND}'
set -U foreground '${FOREGROUND}'
set -U cursor '${FOREGROUND}'
set -U color0 '${BACKGROUND}'
set -U color1 '${RED}'
set -U color2 '${GREEN}'
set -U color3 '${YELLOW}'
set -U color4 '${BLUE}'
set -U color5 '${MAGENTA}'
set -U color6 '${CYAN}'
set -U color7 '${FOREGROUND}'
set -U color8 '${COMMENT}'
set -U color9 '${RED}'
set -U color10 '${GREEN}'
set -U color11 '${YELLOW}'
set -U color12 '${BLUE}'
set -U color13 '${MAGENTA}'
set -U color14 '${CYAN}'
set -U color15 '${BRIGHT_WHITE}'

set -U fish_color_normal normal
set -U fish_color_command green
set -U fish_color_param cyan
set -U fish_pager_color_completion
set -U fish_pager_color_description \$fish_color_quote yellow
set -U fish_pager_color_progress brwhite --background=cyan
set -U fish_color_history_current --bold
TOKENS

cat > "${ROOT_DIR}/fzf.fish" <<TOKENS
# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
set -l color00 '${BACKGROUND}'
set -l color01 '${RED}'
set -l color02 '${GREEN}'
set -l color03 '${YELLOW}'
set -l color04 '${BLUE}'
set -l color05 '${MAGENTA}'
set -l color06 '${CYAN}'
set -l color07 '${FOREGROUND}'
set -l color08 '${COMMENT}'
set -l color09 '${RED}'
set -l color0A '${GREEN}'
set -l color0B '${YELLOW}'
set -l color0C '${BLUE}'
set -l color0D '${MAGENTA}'
set -l color0E '${CYAN}'
set -l color0F '${BRIGHT_WHITE}'

set -l FZF_NON_COLOR_OPTS

for arg in (echo \$FZF_DEFAULT_OPTS | tr " " "\\n")
    if not string match -q -- "--color*" \$arg
        set -a FZF_NON_COLOR_OPTS \$arg
    end
end

set -Ux FZF_DEFAULT_OPTS "\$FZF_NON_COLOR_OPTS"" --color=bg+:\$color00,bg:\$color00,spinner:\$color0E,hl:\$color0D"" --color=fg:\$color07,header:\$color0D,info:\$color0A,pointer:\$color0E"" --color=marker:\$color0E,fg+:\$color06,prompt:\$color0A,hl+:\$color0D"
TOKENS

cat > "${ROOT_DIR}/waybar.css" <<TOKENS
/* AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh */
@define-color background ${BACKGROUND};
@define-color foreground ${FOREGROUND};
TOKENS

cat > "${ROOT_DIR}/waybar-theme/config.jsonc" <<'TOKENS'
// AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
{
  "reload_style_on_change": true,
  "layer": "top",
  "position": "top",
  "mod": "dock",
  "margin-top": 0,
  "height": __WAYBAR_HEIGHT_PX__,
  "margin-left": 0,
  "margin-right": 0,
  "margin-bottom": 0,
  "modules-left": [
    "custom/omarchy",
    "hyprland/workspaces",
    "custom/screenrecording-indicator",
    "custom/updatespacman",
    "custom/update",
    "mpris"
  ],
  "modules-center": [
    "custom/weather",
    "clock",
    "idle_inhibitor"
  ],
  "modules-right": [
    "tray",
    "backlight",
    "bluetooth",
    "pulseaudio",
    "network",
    "memory",
    "battery",
    "cpu"
  ],
  "hyprland/workspaces": {
    "on-click": "activate",
    "disable-scroll": true,
    "tooltip": false
  },
  "custom/omarchy": {
    "format": "<span font='omarchy'>\ue900</span>",
    "on-click": "omarchy-menu",
    "on-click-right": "xdg-terminal-exec",
    "tooltip-format": "Omarchy Menu\n\nSuper + Alt + Space"
  },
  "custom/update": {
    "format": "",
    "exec": "omarchy-update-available",
    "on-click": "omarchy-launch-floating-terminal-with-presentation omarchy-update",
    "tooltip-format": "Omarchy update available",
    "signal": 7,
    "interval": 21600
  },
  "custom/updatespacman": {
    "format": "{}{icon}",
    "return-type": "json",
    "format-icons": {
      "has-updates": " 󰏖",
      "updated": ""
    },
    "exec-if": "which waybar-module-pacman-updates",
    "exec": "waybar-module-pacman-updates --no-zero-output"
  },
  "hyprland/window": {
    "format": "{title} - {class}",
    "max-length": 85,
    "rewrite": {
      " - ": "", // if no window is focused, a single dash is displayed, this removes it
      "(.*?) - Chromium - chromium": "   $1 ",
      "(.*chrome)...(.*)": "   $1 ",
      "(.*) - Obsidian - .* - obsidian": "   $1 ",
      "(.*nvim)...(.*)": "   $2 ",
      "(.*code) - (.*)": " 󰨞  $1 ",
      "^.*btop( .*|$)": " 󰧨 BTOP $1 ",
      "^.*cmatrix( .*|$)": " 󰘨 MATRIX $1 ",
      "(.*) - Spotify": "  $1 ",
      "(.*) - com.mitchellh.ghostty": " 󰊠 $1 ",
      "(.*) - Alacritty": "   $1 ",
      "(.*) - BeeperTexts": " 󰻞  $1 ",
      "(.*Discord)...(.*).. (.*)": "   $2 ",
      "(.*) - org.gnome.Nautilus": " 󰣆  $1 ",
      "(.*) - fish": "   [$1] ",
      "(.*Steam)...(.*)": "   $1",
      "(.*imv)...(.*).. (.*)": "   $2",
      "(.*) - com.obsproject.Studio": "  $1 "
    }
  },
  "cpu": {
    "interval": 2,
    "format": "{usage}% 󰍛",
    "on-click": "omarchy-launch-or-focus-tui btop"
  },
  "memory": {
    "interval": 2,
    "format": "{percentage}%  ",
    "on-click": "omarchy-launch-or-focus-tui btop"
  },
  "clock": {
    "format": " {:%I:%M %p %A %d}",
    "format-alt": " {:%d/%m/%Y  %I:%M:%S %p}",
    "tooltip-format": "<span>{calendar}</span>",
    "calendar": {
      "mode": "month",
      "weeks-pos": "right",
      "mode-mon-col": 3,
      "on-click-right": "mode",
      "format": {
        "month": "<span color='__WAYBAR_CALENDAR_MONTH_COLOR__'><b>{}</b></span>",
        "weekdays": "<span color='__WAYBAR_CALENDAR_WEEKDAY_COLOR__'><b>{}</b></span>",
        "today": "<span color='__WAYBAR_CALENDAR_TODAY_COLOR__'><b>{}</b></span>"
      }
    },
    "on-click-right": "omarchy-launch-floating-terminal-with-presentation omarchy-tz-select"
  },
  "idle_inhibitor": {
    "format": "{icon}",
    "format-icons": {
      "activated": "󰛊",
      "deactivated": "󰾫"
    }
  },
  "network": {
    "format-icons": [
      "󰤯",
      "󰤟",
      "󰤢",
      "󰤥",
      "󰤨"
    ],
    "format": "{icon}",
    "format-wifi": "{icon}",
    "format-ethernet": "󰀂",
    "format-disconnected": "󰖪",
    "tooltip-format-wifi": "{essid} ({frequency} GHz)\n⇣{bandwidthDownBytes}  ⇡{bandwidthUpBytes}",
    "tooltip-format-ethernet": "⇣{bandwidthDownBytes}  ⇡{bandwidthUpBytes}",
    "tooltip-format-disconnected": "Disconnected",
    "interval": 3,
    "nospacing": 1,
    "on-click": "alacritty --class=Impala -e impala"
  },
  "battery": {
    "format": "{capacity}% {icon}",
    "format-discharging": "{capacity}% {icon}",
    "format-charging": "{icon}",
    "format-plugged": "{power}",
    "format-icons": {
      "charging": [
        "󰢜",
        "󰂆",
        "󰂇",
        "󰂈",
        "󰢝",
        "󰂉",
        "󰢞",
        "󰂊",
        "󰂋",
        "󰂅"
      ],
      "default": [
        "󰁺",
        "󰁻",
        "󰁼",
        "󰁽",
        "󰁾",
        "󰁿",
        "󰂀",
        "󰂁",
        "󰂂",
        "󰁹"
      ]
    },
    "format-full": "󰂅",
    "tooltip-format-discharging": "{timeTo}",
    "tooltip-format-charging": "{timeTo}",
    "interval": 5,
    "states": {
      "warning": 20,
      "critical": 10
    }
  },
  "bluetooth": {
    "format": "",
    "format-disabled": "󰂲",
    "format-off": "󰂲",
    "format-connected": "",
    "tooltip-format": "Devices connected: {num_connections}",
    "on-click": "omarchy-launch-bluetooth"
  },
  "backlight": {
    "format": "{icon}",
    "tooltip-format": "{percent}%",
    "format-icons": [
      "🌑",
      "🌘",
      "🌗",
      "🌖",
      "🌕"
    ]
  },
  "custom/weather": {
    "format": "{}°",
    "tooltip": true,
    "interval": 1800,
    "exec": "wttrbar --nerd --location yourlocation",
    "return-type": "json"
  },
  "pulseaudio": {
    "format": "{icon}",
    "on-click": "omarchy-launch-or-focus-tui wiremix",
    "on-click-right": "pamixer -t",
    "tooltip-format": "Playing at {volume}%",
    "scroll-step": 5,
    "format-muted": "",
    "format-icons": {
      "default": [
        "",
        "",
        " "
      ]
    }
  },
  "tray": {
    "icon-size": __WAYBAR_SYSTEM_ICON_SIZE_PX__,
    "spacing": 6
  },
  "mpris": {
    "format": "{player_icon} {dynamic}",
    "format-paused": "{status_icon} {dynamic}",
    "max-length": 55,
    "interval": 1,
    "player-icons": {
      "default": "",
      "mpv": "🎵"
    },
    "status-icons": {
      "paused": ""
    }
    // "ignored-players": ["firefox"]
  },
  "custom/screenrecording-indicator": {
    "on-click": "omarchy-cmd-screenrecord",
    "exec": "$OMARCHY_PATH/default/waybar/indicators/screen-recording.sh",
    "signal": 8,
    "return-type": "json"
  }
}
TOKENS

sed -i \
  -e "s|__WAYBAR_HEIGHT_PX__|${WAYBAR_HEIGHT_PX}|g" \
  -e "s|__WAYBAR_SYSTEM_ICON_SIZE_PX__|${WAYBAR_SYSTEM_ICON_SIZE_PX}|g" \
  -e "s|__WAYBAR_CALENDAR_MONTH_COLOR__|${WAYBAR_CALENDAR_MONTH_COLOR}|g" \
  -e "s|__WAYBAR_CALENDAR_WEEKDAY_COLOR__|${WAYBAR_CALENDAR_WEEKDAY_COLOR}|g" \
  -e "s|__WAYBAR_CALENDAR_TODAY_COLOR__|${WAYBAR_CALENDAR_TODAY_COLOR}|g" \
  "${ROOT_DIR}/waybar-theme/config.jsonc"

cat > "${ROOT_DIR}/waybar-theme/style.css" <<TOKENS
/* AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh */
@import "../omarchy/current/theme/waybar.css";

@define-color background ${BACKGROUND};
@define-color base ${BACKGROUND};
@define-color surface ${SURFACE};
@define-color overlay ${OVERLAY};
@define-color muted ${COMMENT};
@define-color subtle ${SUBTLE};
@define-color text ${FOREGROUND};
@define-color love ${MAGENTA};
@define-color gold ${YELLOW};
@define-color rose ${ORANGE};
@define-color pine ${CYAN};
@define-color foam ${GREEN};
@define-color iris ${BLUE};
@define-color highlight_low ${OVERLAY};
@define-color highlight_med ${SELECTION};
@define-color highlight_high ${COMMENT};
@define-color neutral_bg ${WAYBAR_NEUTRAL_BG};
@define-color neutral_bg_alt ${WAYBAR_NEUTRAL_BG_ALT};
@define-color neutral_text ${WAYBAR_NEUTRAL_TEXT};
@define-color muted_text ${WAYBAR_MUTED_TEXT};
@define-color accent_cool ${WAYBAR_ACCENT_COOL};
@define-color accent_warm ${WAYBAR_ACCENT_WARM};
@define-color accent_power ${WAYBAR_ACCENT_POWER};
@define-color alert_bg ${WAYBAR_ALERT_BG};
@define-color alert_text ${WAYBAR_ALERT_TEXT};
@define-color state_ok ${WAYBAR_STATE_OK};
@define-color state_info ${WAYBAR_STATE_INFO};
@define-color state_warning ${WAYBAR_STATE_WARNING};
@define-color state_muted ${WAYBAR_STATE_MUTED};
@define-color state_alert ${WAYBAR_STATE_ALERT};
@define-color item_hover_bg ${WAYBAR_HOVER_BG};

* {
  font-family: "JetBrainsMono Nerd Font Propo";
  font-size: ${WAYBAR_THEME_FONT_SIZE_PX}px;
  font-weight: bold;
  min-height: 0;
}

window#waybar {
  background-color: @neutral_bg;
  transition-property: background-color;
  transition-duration: 0.5s;
}

window#waybar.empty #window {
  background: @neutral_bg;
  border: none;
  border-radius: 0;
  color: @neutral_text;
  padding: 0;
  margin: 0;
}

#waybar.empty .modules-center {
  opacity: 0;
}

.modules-left,
.modules-center,
.modules-right,
#workspaces {
  background-color: @neutral_bg;
}

tooltip {
  opacity: 1;
  padding: 4px;
  background-color: @surface;
  border: 1px solid @highlight_med;
  border-radius: 4px;
  font-size: 12px;
}

tooltip label {
  color: @text;
  font-weight: normal;
}

#workspaces {
  border-radius: 0;
  margin: 0 1px;
}

#workspaces button {
  padding: ${WAYBAR_WORKSPACE_PADDING};
  margin: ${WAYBAR_WORKSPACE_MARGIN};
  font-size: ${WAYBAR_WORKSPACE_FONT_SIZE_PX}px;
  border-radius: ${WAYBAR_ITEM_RADIUS_PX}px;
  background-color: @neutral_bg;
  color: @text;
  min-height: ${WAYBAR_HEIGHT_PX}px;
  border: none;
  box-shadow: none;
  outline: none;
  transition: background-color 120ms ease, color 120ms ease;
}

#workspaces button.active {
  background-color: @item_hover_bg;
  color: @accent_warm;
  border-radius: ${WAYBAR_ITEM_RADIUS_PX}px;
  border: none;
  box-shadow: none;
  outline: none;
}

#workspaces button:hover {
  background-color: @item_hover_bg;
  color: @neutral_text;
  border-radius: ${WAYBAR_ITEM_RADIUS_PX}px;
  border: none;
  box-shadow: none;
  outline: none;
}

#tray,
#window,
#mpris,
#cpu,
#clock,
#battery,
#network,
#memory,
#backlight,
#bluetooth,
#pulseaudio,
#custom-weather,
#custom-update,
#idle_inhibitor,
#custom-omarchy,
#custom-screenrecording-indicator,
#custom-updatespacman {
  min-width: ${WAYBAR_MODULE_MIN_WIDTH}px;
  min-height: ${WAYBAR_HEIGHT_PX}px;
  margin: ${WAYBAR_MODULE_MARGIN};
  padding: ${WAYBAR_MODULE_PADDING};
  border-radius: ${WAYBAR_ITEM_RADIUS_PX}px;
  border: none;
  box-shadow: none;
  outline: none;
  transition: background-color 120ms ease, color 120ms ease;
}

#clock:hover,
#tray:hover,
#custom-expand-icon:hover,
#cpu:hover,
#memory:hover,
#temperature:hover,
#battery:hover,
#bluetooth:hover,
#backlight:hover,
#custom-omarchy:hover,
#custom-weather:hover,
#custom-update:hover,
#idle_inhibitor:hover,
#custom-screenrecording-indicator:hover,
#custom-updatespacman:hover,
#network:hover,
#pulseaudio:hover {
  border-radius: ${WAYBAR_ITEM_RADIUS_PX}px;
  background-color: @item_hover_bg;
  color: @neutral_text;
}

#backlight,
#battery,
#network,
#pulseaudio,
#bluetooth {
  font-size: ${WAYBAR_SYSTEM_ICON_SIZE_PX}px;
  min-width: ${WAYBAR_RIGHT_ICON_MIN_WIDTH_PX}px;
  padding: 0;
}

#cpu,
#memory {
  font-size: ${WAYBAR_RESOURCE_ICON_SIZE_PX}px;
}

#window {
  background-color: @neutral_bg_alt;
  color: @accent_warm;
}

#custom-omarchy {
  background-color: @neutral_bg;
  color: @accent_warm;
  font-size: ${WAYBAR_OMARCHY_ICON_SIZE_PX}px;
}

#custom-update,
#custom-updatespacman {
  background-color: @neutral_bg;
  color: @accent_power;
}

#clock {
  background-color: @neutral_bg;
  color: @accent_warm;
  font-size: ${WAYBAR_CLOCK_FONT_SIZE_PX}px;
}

#idle_inhibitor,
#idle_inhibitor.deactivated {
  background-color: @neutral_bg;
  color: @muted_text;
  font-size: ${WAYBAR_IDLE_ICON_SIZE_PX}px;
}

#idle_inhibitor.activated {
  background-color: @neutral_bg;
  color: @accent_power;
  font-size: ${WAYBAR_IDLE_ICON_SIZE_PX}px;
}

#custom-weather {
  background-color: @neutral_bg_alt;
  color: @accent_cool;
}

#tray {
  background-color: @neutral_bg_alt;
  color: @accent_warm;
}

#battery {
  background-color: @neutral_bg;
  color: @accent_power;
}

#cpu {
  background-color: @neutral_bg;
  color: @accent_warm;
}

#memory {
  background-color: @neutral_bg;
  color: @accent_warm;
}

#network {
  background-color: @neutral_bg;
  color: @accent_cool;
}

#pulseaudio {
  background-color: @neutral_bg;
  color: @accent_cool;
}

#backlight {
  background-color: @neutral_bg;
  color: @accent_cool;
}

#bluetooth {
  background-color: @neutral_bg;
  color: @accent_cool;
}

/* Dynamic state colors (One Dark semantic mapping) */
#network.disconnected,
#network.disabled {
  color: @state_warning;
}

#bluetooth.off,
#bluetooth.disabled,
#bluetooth.no-controller {
  color: @state_muted;
}

#bluetooth.connected {
  color: @state_ok;
}

#pulseaudio.muted {
  color: @state_muted;
}

#battery.charging {
  color: @state_ok;
}

#mpris {
  background-color: @neutral_bg_alt;
  color: @neutral_text;
}

#mpris.paused {
  color: @muted_text;
}

#tray > .passive {
  -gtk-icon-effect: dim;
  color: @accent_warm;
}

#tray > .needs-attention {
  -gtk-icon-effect: highlight;
  background-color: @neutral_bg_alt;
  color: @accent_warm;
}

#tray * {
  color: @accent_warm;
}

.hidden {
  opacity: 0;
}

#cpu.critical,
#memory.critical,
#battery.warning,
#battery.critical,
#battery.urgent {
  background-color: @alert_bg;
  color: @alert_text;
}

#custom-screenrecording-indicator {
  animation-timing-function: linear;
  animation-iteration-count: infinite;
  animation-direction: alternate;
  color: @surface;
}

#custom-screenrecording-indicator.active {
  color: @love;
  animation-name: blink-recording;
  animation-duration: 0.5s;
}

@keyframes blink-recording {
  to {
    color: @surface;
  }
}

TOKENS

cat > "${ROOT_DIR}/walker.css" <<TOKENS
/* AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh */
@define-color selected-text ${WALKER_SELECTED_TEXT};
@define-color text ${WALKER_TEXT};
@define-color base ${WALKER_BASE_BG};
@define-color border ${WALKER_BORDER};
@define-color foreground ${WALKER_TEXT};
@define-color background ${WALKER_SEARCH_BG};
@define-color input ${WALKER_INPUT_BG};
@define-color hover-box ${WALKER_HOVER_BG};
@define-color selected-box ${WALKER_SELECTED_BG};

window {
  background-color: transparent;
  border: none;
  border-width: 0;
  border-color: @border;
  padding: 0;
  box-shadow: none;
}

.search-container {
  background: transparent;
  border: none;
  border-radius: ${WALKER_RADIUS}px;
  padding: 0;
}

window .box-wrapper {
  border-radius: ${WALKER_RADIUS}px;
  border: 1px solid @border;
  padding: ${WALKER_WRAPPER_PADDING_Y}px ${WALKER_WRAPPER_PADDING_X}px;
  background: @base;
  background-color: @base;
}

window .search-container {
  background: transparent;
  background-color: transparent;
}

#entry entry,
.input {
  background-color: @input;
  color: @foreground;
  border-radius: ${WALKER_RADIUS}px;
  padding: ${WALKER_INPUT_PADDING_Y}px ${WALKER_ALIGNED_PADDING_X}px;
  border: 1px solid @border;
  background-image: none;
  box-shadow: none;
  outline: none;
}

#entry * {
  background-color: @input;
  background-image: none;
  box-shadow: none;
}

#entry:selected {
  color: @foreground;
}

child {
  padding: ${WALKER_ITEM_GAP_Y}px ${WALKER_ITEM_GAP_X}px;
}

child .item-box {
  border-radius: ${WALKER_RADIUS}px;
  border: none;
  background: @base;
}

child:hover .item-box {
  background-image: none;
  border: none;
  background-color: @hover-box;
  border-radius: ${WALKER_RADIUS}px;
  box-shadow: none;
}

child:selected .item-box {
  background-image: none;
  border: none;
  background-color: @selected-box;
  border-radius: ${WALKER_RADIUS}px;
  box-shadow: none;
}

child .item-text {
  color: @foreground;
}

window .item-box {
  padding: 0 ${WALKER_ALIGNED_PADDING_X}px;
}

window .item-text-box {
  padding: ${WALKER_ITEM_TEXT_PADDING_Y}px 0;
}

window .item-image {
  margin-right: ${WALKER_ITEM_IMAGE_GAP}px;
}

child:hover .item-text {
  color: @foreground;
}

child:selected .item-text {
  color: @selected-text;
}

window .box-wrapper #entry,
window .box-wrapper #entry * {
  background: @input;
  background-color: @input;
  background-image: none;
  box-shadow: none;
  outline: none;
}
TOKENS

cat > "${ROOT_DIR}/gtk.css" <<TOKENS
/* AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh */

@define-color background ${BACKGROUND};
@define-color foreground ${FOREGROUND};
@define-color black ${BACKGROUND};
@define-color red ${RED};
@define-color green ${GREEN};
@define-color yellow ${YELLOW};
@define-color blue ${BLUE};
@define-color magenta ${MAGENTA};
@define-color cyan ${CYAN};
@define-color white ${FOREGROUND};
@define-color bright_black ${COMMENT};
@define-color bright_red ${BRIGHT_RED};
@define-color bright_green ${BRIGHT_GREEN};
@define-color bright_yellow ${BRIGHT_YELLOW};
@define-color bright_blue ${BRIGHT_BLUE};
@define-color bright_magenta ${BRIGHT_MAGENTA};
@define-color bright_cyan ${BRIGHT_CYAN};
@define-color bright_white ${BRIGHT_WHITE};

@define-color accent_bg_color @blue;
@define-color accent_fg_color @background;
@define-color accent_color @cyan;

@define-color window_bg_color @background;
@define-color window_fg_color @foreground;
@define-color view_bg_color @black;
@define-color view_fg_color @foreground;
@define-color sidebar_bg_color @black;
@define-color sidebar_fg_color @foreground;
@define-color sidebar_backdrop_color @black;
@define-color sidebar_shade_color @black;
@define-color headerbar_bg_color @background;
@define-color headerbar_fg_color @foreground;
@define-color headerbar_backdrop_color @black;
@define-color headerbar_shade_color @black;
@define-color card_bg_color @background;
@define-color card_fg_color @foreground;
@define-color popover_bg_color @black;
@define-color popover_fg_color @foreground;
@define-color destructive_bg_color @red;
@define-color destructive_fg_color @background;
@define-color success_bg_color @green;
@define-color success_fg_color @background;
@define-color warning_bg_color @yellow;
@define-color warning_fg_color @background;
@define-color error_bg_color @red;
@define-color error_fg_color @background;
@define-color dialog_bg_color @background;
@define-color dialog_fg_color @foreground;

@define-color borders alpha(@foreground, 0.1);

@define-color theme_fg_color @foreground;
@define-color theme_text_color @foreground;
@define-color theme_bg_color @background;
@define-color theme_base_color @black;
@define-color theme_selected_bg_color @blue;
@define-color theme_selected_fg_color @background;

messagedialog,
alertdialog.background,
filechooser,
popover,
toast,
window {
  background-color: @background;
  color: @foreground;
}

messagedialog label,
alertdialog label {
  color: @dialog_fg_color;
}

messagedialog button {
  background-color: @black;
  color: @foreground;
  border: 1px solid @bright_black;
  padding: 10px;
}

messagedialog button:hover {
  background-color: @blue;
}

banner revealer widget {
  background: @bright_black;
  padding: 5px;
  color: @foreground;
}

alertdialog .titlebar {
  background-color: @headerbar_bg_color;
  color: @headerbar_fg_color;
}

filechooser .dialog-action-box {
  border-top: 1px solid @bright_black;
}

filechooser .dialog-action-box:backdrop {
  border-top-color: @black;
}

filechooser #pathbarbox {
  border-bottom: 1px solid @bright_black;
}

filechooserbutton:drop(active) {
  box-shadow: none;
  border-color: transparent;
}

toast button.circular.flat.image-button:hover {
  color: @background;
  background-color: @red;
}
TOKENS

cat > "${ROOT_DIR}/steam.css" <<TOKENS
/* AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh */
:root {
  --adw-accent-bg-rgb: ${BLUE_RGB} !important;
  --adw-accent-fg-rgb: ${BACKGROUND_RGB} !important;
  --adw-accent-rgb: ${BLUE_RGB} !important;

  --adw-destructive-bg-rgb: ${RED_RGB} !important;
  --adw-destructive-fg-rgb: ${FOREGROUND_RGB} !important;
  --adw-destructive-rgb: ${RED_RGB} !important;

  --adw-success-bg-rgb: ${GREEN_RGB} !important;
  --adw-success-rgb: ${GREEN_RGB} !important;

  --adw-warning-bg-rgb: ${YELLOW_RGB} !important;
  --adw-warning-rgb: ${YELLOW_RGB} !important;

  --adw-error-bg-rgb: ${RED_RGB} !important;
  --adw-error-rgb: ${RED_RGB} !important;

  --adw-window-bg-rgb: ${BACKGROUND_RGB} !important;
  --adw-window-fg-rgb: ${FOREGROUND_RGB} !important;

  --adw-view-bg-rgb: ${SURFACE_RGB} !important;
  --adw-view-fg-rgb: ${FOREGROUND_RGB} !important;

  --adw-headerbar-bg-rgb: ${BACKGROUND_RGB} !important;
  --adw-headerbar-fg-rgb: ${FOREGROUND_RGB} !important;
  --adw-headerbar-border-rgb: ${COMMENT_RGB} !important;
  --adw-headerbar-backdrop-rgb: ${SURFACE_RGB} !important;
  --adw-headerbar-shade-rgb: 0, 0, 0 !important;
  --adw-headerbar-shade-a: 0.36 !important;

  --adw-sidebar-bg-rgb: ${BACKGROUND_RGB} !important;
  --adw-sidebar-fg-rgb: ${FOREGROUND_RGB} !important;
  --adw-sidebar-backdrop-rgb: ${COMMENT_RGB} !important;
  --adw-sidebar-shade-rgb: 0, 0, 0 !important;
  --adw-sidebar-shade-a: 0.36 !important;

  --adw-card-bg-rgb: ${BRIGHT_WHITE_RGB} !important;
  --adw-card-bg-a: 0.08 !important;
  --adw-card-fg-rgb: ${BRIGHT_WHITE_RGB} !important;

  --adw-dialog-bg-rgb: ${BACKGROUND_RGB} !important;
  --adw-dialog-fg-rgb: ${FOREGROUND_RGB} !important;

  --adw-popover-bg-rgb: ${BACKGROUND_RGB} !important;
  --adw-popover-fg-rgb: ${FOREGROUND_RGB} !important;

  --adw-thumbnail-bg-rgb: ${BACKGROUND_RGB} !important;
}
TOKENS

cat > "${ROOT_DIR}/cava_theme" <<TOKENS
# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
[color]
gradient = 1
gradient_count = 8
gradient_color_1 = '${CYAN}'
gradient_color_2 = '${BLUE}'
gradient_color_3 = '${BRIGHT_BLUE}'
gradient_color_4 = '${MAGENTA}'
gradient_color_5 = '${BRIGHT_MAGENTA}'
gradient_color_6 = '${BRIGHT_CYAN}'
gradient_color_7 = '${BRIGHT_MAGENTA}'
gradient_color_8 = '${CYAN}'
TOKENS

cat > "${ROOT_DIR}/hyprland.conf" <<TOKENS
# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh

general {
    col.active_border = rgba(${BLUE_NOHASH}dd) rgba(${CYAN_NOHASH}dd) 65deg
    col.inactive_border = rgba(${COMMENT_NOHASH}aa)
}

decoration {
    rounding = 0

    shadow {
        enabled = true
        range = 8
        render_power = 4
        offset = 0 0
        ignore_window = false
        color = rgba(${BLUE_NOHASH}33)
        color_inactive = rgba(${COMMENT_NOHASH}22)
    }
}

# Remove default opacity tag from Omarchy defaults before global opacity rule applies.
windowrule = tag -default-opacity, match:class .*

# Window opacity control: keep active and inactive windows fully solid.
windowrule = opacity ${WINDOW_OPACITY} override ${WINDOW_OPACITY} override, match:class .*
TOKENS

cat > "${ROOT_DIR}/vencord.theme.css" <<TOKENS
/**
 * AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
 * @name One Dark Pro Flat | based on midnight by refact0r
 * @description A dark One Dark Pro theme for Discord
 * @author One Dark Pro Adaptation
 * @version 3.4
 */

@import url('https://refact0r.github.io/midnight-discord/build/midnight.css');

body {
    --font: 'figtree';
    --code-font: '';
    font-weight: 400;
    --gap: 12px;
    --divider-thickness: 4px;
    --border-thickness: 2px;
    --animations: on;
    --list-item-transition: 0.2s ease;
    --dms-icon-svg-transition: 0.4s ease;
    --border-hover-transition: 0.2s ease;
    --top-bar-height: var(--gap);
    --top-bar-button-position: titlebar;
    --top-bar-title-position: off;
    --subtle-top-bar-title: off;
    --custom-window-controls: on;
    --window-control-size: 14px;
    --custom-dms-icon: off;
    --dms-icon-svg-url: url('');
    --dms-icon-svg-size: 90%;
    --dms-icon-color-before: var(--icon-secondary);
    --dms-icon-color-after: var(--white);
    --custom-dms-background: off;
    --dms-background-image-url: url('');
    --dms-background-image-size: cover;
    --dms-background-color: linear-gradient(70deg, var(--blue-2), var(--purple-2), var(--red-2));
    --background-image: off;
    --background-image-url: url('');
    --transparency-tweaks: off;
    --remove-bg-layer: off;
    --panel-blur: off;
    --blur-amount: 12px;
    --bg-floating: var(--bg-3);
    --custom-chatbar: aligned;
    --chatbar-height: 47px;
    --chatbar-padding: 8px;
    --small-user-panel: on;
}

:root {
    --colors: on;
    --text-0: ${BACKGROUND};
    --text-1: ${FOREGROUND};
    --text-2: ${CYAN};
    --text-3: ${FOREGROUND};
    --text-4: ${COMMENT};
    --text-5: ${COMMENT};
    --bg-1: ${BACKGROUND};
    --bg-2: ${BACKGROUND};
    --bg-3: ${BACKGROUND};
    --bg-4: ${BACKGROUND};
    --hover: ${SELECTION};
    --active: ${SELECTION};
    --active-2: ${SELECTION};
    --message-hover: ${SELECTION};
    --accent-1: ${BLUE};
    --accent-2: ${BLUE};
    --accent-3: ${BLUE};
    --accent-4: ${BLUE};
    --accent-5: ${BLUE};
    --accent-new: ${RED};
    --mention: linear-gradient(to right, color-mix(in hsl, ${BLUE}, transparent 90%) 40%, transparent);
    --mention-hover: linear-gradient(to right, color-mix(in hsl, ${BLUE}, transparent 95%) 40%, transparent);
    --reply: linear-gradient(to right, color-mix(in hsl, ${FOREGROUND}, transparent 90%) 40%, transparent);
    --reply-hover: linear-gradient(to right, color-mix(in hsl, ${FOREGROUND}, transparent 95%) 40%, transparent);
    --online: ${GREEN};
    --dnd: ${RED};
    --idle: ${YELLOW};
    --streaming: ${BLUE};
    --offline: ${COMMENT};
    --border-light: ${SELECTION};
    --border: ${SELECTION};
    --border-hover: ${BLUE};
    --button-border: ${SELECTION};
    --red: ${RED};
    --orange: ${ORANGE};
    --yellow: ${YELLOW};
    --green: ${GREEN};
    --cyan: ${CYAN};
    --purple: ${BLUE};
    --pink: ${MAGENTA};
}

*,
*::before,
*::after {
    border-radius: 0 !important;
}
TOKENS

cat > "${ROOT_DIR}/lazygit.yml" <<TOKENS
# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
theme:
  activeBorderColor:
    - "${MAGENTA}"
    - bold
  inactiveBorderColor:
    - "${BLUE}"
  searchingActiveBorderColor:
    - "${CYAN}"
    - bold
  optionsTextColor:
    - "${COMMENT}"
  selectedLineBgColor:
    - "${COMMENT}"
  inactiveViewSelectedLineBgColor:
    - bold
  cherryPickedCommitFgColor:
    - "${COMMENT}"
  cherryPickedCommitBgColor:
    - "${CYAN}"
  markedBaseCommitFgColor:
    - "${CYAN}"
  markedBaseCommitBgColor:
    - "${YELLOW}"
  unstagedChangesColor:
    - "${RED}"
  defaultFgColor:
    - "${FOREGROUND}"
TOKENS

cat > "${ROOT_DIR}/neovim.lua" <<TOKENS
-- AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
return {
  {
    "olimorris/onedarkpro.nvim",
    priority = 1000,
    config = function()
      require("onedarkpro").setup({
        theme = "onedark",
        highlights = {
          LineNr = { fg = "${COMMENT}", bg = "bg" },
          TabLineFill = { bg = "bg" },
          TabLine = { bg = "bg" },
          TabLineSel = { bg = "${BACKGROUND}" },
        },
      })
      vim.cmd("colorscheme onedark")
    end,
  },
}
TOKENS

cat > "${ROOT_DIR}/starship.toml" <<'TOKENS'
# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
add_newline = false
command_timeout = 200
format = "$directory$git_branch$git_status$python$conda$pixi$line_break$character"

palette = "onedark_flat"

[palettes.onedark_flat]
background = "__BACKGROUND__"
surface = "__SURFACE__"
overlay = "__OVERLAY__"
text = "__FOREGROUND__"
text_strong = "__FOREGROUND_BRIGHT__"
muted = "__SUBTLE__"
blue = "__BLUE__"
green = "__GREEN__"
yellow = "__YELLOW__"
magenta = "__MAGENTA__"
red = "__RED__"
cyan = "__CYAN__"

[directory]
style = "bold fg:background bg:blue"
format = "[ __PROMPT_DIRECTORY_ICON__ $read_only$path ]($style)"
truncation_length = __PROMPT_DIRECTORY_TRUNCATION_LENGTH__
truncation_symbol = "__PROMPT_DIRECTORY_TRUNCATION_SYMBOL__"
truncate_to_repo = false
read_only = "__PROMPT_READ_ONLY_ICON__ "
read_only_style = "fg:red bg:blue"
repo_root_style = "bold fg:background bg:blue"
repo_root_format = "[ __PROMPT_DIRECTORY_ICON__ $read_only$repo_root$path ]($repo_root_style)"

[git_branch]
symbol = "__PROMPT_GIT_ICON__ "
style = "fg:text_strong bg:surface"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "fg:yellow bg:surface"
format = "[ $all_status$ahead_behind ]($style)"
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
conflicted = " "
up_to_date = ""
untracked = "? "
modified = "! "
stashed = "* "
staged = "+ "
renamed = "» "
deleted = "✕ "

[python]
symbol = "__PROMPT_PYTHON_ICON__ "
style = "fg:green bg:overlay"
format = "[ $symbol${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
detect_extensions = []
detect_files = ["pyproject.toml", "requirements.txt", "Pipfile", "tox.ini", "setup.py"]

[conda]
symbol = "__PROMPT_CONDA_ICON__ "
style = "fg:cyan bg:overlay"
format = "[ $symbol$environment ]($style)"

[pixi]
symbol = "__PROMPT_PIXI_ICON__ "
style = "fg:magenta"
format = "[ $symbol$environment ](fg:magenta bg:overlay)"

[line_break]
disabled = false

[character]
success_symbol = "[╰─❯](bold blue)"
error_symbol = "[╰─❯](bold red)"
vimcmd_symbol = "[╰─❮](bold yellow)"
TOKENS

sed -i \
  -e "s|__BACKGROUND__|${BACKGROUND}|g" \
  -e "s|__SURFACE__|${SURFACE}|g" \
  -e "s|__OVERLAY__|${OVERLAY}|g" \
  -e "s|__FOREGROUND__|${FOREGROUND}|g" \
  -e "s|__FOREGROUND_BRIGHT__|${FOREGROUND_BRIGHT}|g" \
  -e "s|__SUBTLE__|${SUBTLE}|g" \
  -e "s|__BLUE__|${BLUE}|g" \
  -e "s|__GREEN__|${GREEN}|g" \
  -e "s|__YELLOW__|${YELLOW}|g" \
  -e "s|__MAGENTA__|${MAGENTA}|g" \
  -e "s|__RED__|${RED}|g" \
  -e "s|__CYAN__|${CYAN}|g" \
  -e "s|__PROMPT_DIRECTORY_TRUNCATION_LENGTH__|${PROMPT_DIRECTORY_TRUNCATION_LENGTH}|g" \
  -e "s|__PROMPT_DIRECTORY_TRUNCATION_SYMBOL__|${PROMPT_DIRECTORY_TRUNCATION_SYMBOL}|g" \
  -e "s|__PROMPT_READ_ONLY_ICON__|${PROMPT_READ_ONLY_ICON}|g" \
  -e "s|__PROMPT_DIRECTORY_ICON__|${PROMPT_DIRECTORY_ICON}|g" \
  -e "s|__PROMPT_GIT_ICON__|${PROMPT_GIT_ICON}|g" \
  -e "s|__PROMPT_PYTHON_ICON__|${PROMPT_PYTHON_ICON}|g" \
  -e "s|__PROMPT_CONDA_ICON__|${PROMPT_CONDA_ICON}|g" \
  -e "s|__PROMPT_PIXI_ICON__|${PROMPT_PIXI_ICON}|g" \
  "${ROOT_DIR}/starship.toml"

cat > "${ROOT_DIR}/waybar.css" <<TOKENS
/* AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh */
@define-color background ${BACKGROUND};
@define-color foreground ${FOREGROUND};
TOKENS

cat > "${ROOT_DIR}/waybar-theme/config.jsonc" <<'TOKENS'
// AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
{
  "reload_style_on_change": true,
  "layer": "top",
  "position": "top",
  "spacing": 0,
  "height": __WAYBAR_HEIGHT_PX__,
  "modules-left": ["custom/omarchy", "hyprland/workspaces"],
  "modules-center": [
    "clock",
    "custom/update",
    "custom/voxtype",
    "custom/screenrecording-indicator",
    "custom/idle-indicator",
    "custom/notification-silencing-indicator"
  ],
  "modules-right": [
    "group/tray-expander",
    "bluetooth",
    "network",
    "pulseaudio",
    "cpu",
    "battery"
  ],
  "hyprland/workspaces": {
    "on-click": "activate",
    "format": "{icon}",
    "format-icons": {
      "default": "",
      "1": "1",
      "2": "2",
      "3": "3",
      "4": "4",
      "5": "5",
      "6": "6",
      "7": "7",
      "8": "8",
      "9": "9",
      "10": "0",
      "active": "󱓻"
    },
    "persistent-workspaces": {
      "1": [],
      "2": [],
      "3": [],
      "4": [],
      "5": []
    }
  },
  "custom/omarchy": {
    "format": "<span font='omarchy'>\ue900</span>",
    "on-click": "omarchy-menu",
    "on-click-right": "xdg-terminal-exec",
    "tooltip-format": "Omarchy Menu\n\nSuper + Alt + Space"
  },
  "custom/update": {
    "format": "",
    "exec": "omarchy-update-available",
    "on-click": "omarchy-launch-floating-terminal-with-presentation omarchy-update",
    "tooltip-format": "Omarchy update available",
    "signal": 7,
    "interval": 21600
  },
  "cpu": {
    "interval": 5,
    "format": "󰍛",
    "on-click": "omarchy-launch-or-focus-tui btop"
  },
  "clock": {
    "format": "{:L%A %H:%M}",
    "format-alt": "{:L%d %B W%V %Y}",
    "tooltip": false,
    "on-click-right": "omarchy-launch-floating-terminal-with-presentation omarchy-tz-select"
  },
  "network": {
    "format-icons": ["󰤯", "󰤟", "󰤢", "󰤥", "󰤨"],
    "format": "{icon}",
    "format-wifi": "{icon}",
    "format-ethernet": "󰀂",
    "format-disconnected": "󰤮",
    "tooltip-format-wifi": "{essid} ({frequency} GHz)\n⇣{bandwidthDownBytes}  ⇡{bandwidthUpBytes}",
    "tooltip-format-ethernet": "⇣{bandwidthDownBytes}  ⇡{bandwidthUpBytes}",
    "tooltip-format-disconnected": "Disconnected",
    "interval": 3,
    "spacing": 1,
    "on-click": "omarchy-launch-wifi"
  },
  "battery": {
    "format": "{capacity}% {icon}",
    "format-discharging": "{icon}",
    "format-charging": "{icon}",
    "format-plugged": "",
    "format-icons": {
      "charging": ["󰢜", "󰂆", "󰂇", "󰂈", "󰢝", "󰂉", "󰢞", "󰂊", "󰂋", "󰂅"],
      "default": ["󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
    },
    "format-full": "󰂅",
    "tooltip-format-discharging": "{power:>1.0f}W↓ {capacity}%",
    "tooltip-format-charging": "{power:>1.0f}W↑ {capacity}%",
    "interval": 5,
    "on-click": "omarchy-menu power",
    "states": {
      "warning": 20,
      "critical": 10
    }
  },
  "bluetooth": {
    "format": "",
    "format-off": "󰂲",
    "format-disabled": "󰂲",
    "format-connected": "󰂱",
    "format-no-controller": "",
    "tooltip-format": "Devices connected: {num_connections}",
    "on-click": "omarchy-launch-bluetooth"
  },
  "pulseaudio": {
    "format": "{icon}",
    "on-click": "omarchy-launch-audio",
    "on-click-right": "pamixer -t",
    "tooltip-format": "Playing at {volume}%",
    "scroll-step": 5,
    "format-muted": "",
    "format-icons": {
      "headphone": "",
      "headset": "",
      "default": ["", "", ""]
    }
  },
  "group/tray-expander": {
    "orientation": "inherit",
    "drawer": {
      "transition-duration": 600,
      "children-class": "tray-group-item"
    },
    "modules": ["custom/expand-icon", "tray"]
  },
  "custom/expand-icon": {
    "format": "",
    "tooltip": false,
    "on-scroll-up": "",
    "on-scroll-down": "",
    "on-scroll-left": "",
    "on-scroll-right": ""
  },
  "custom/screenrecording-indicator": {
    "on-click": "omarchy-cmd-screenrecord",
    "exec": "$OMARCHY_PATH/default/waybar/indicators/screen-recording.sh",
    "signal": 8,
    "return-type": "json"
  },
  "custom/idle-indicator": {
    "on-click": "omarchy-toggle-idle",
    "exec": "$OMARCHY_PATH/default/waybar/indicators/idle.sh",
    "signal": 9,
    "return-type": "json"
  },
  "custom/notification-silencing-indicator": {
    "on-click": "omarchy-toggle-notification-silencing",
    "exec": "$OMARCHY_PATH/default/waybar/indicators/notification-silencing.sh",
    "signal": 10,
    "return-type": "json"
  },
  "custom/voxtype": {
    "exec": "omarchy-voxtype-status",
    "return-type": "json",
    "format": "{icon}",
    "format-icons": {
      "idle": "",
      "recording": "󰍬",
      "transcribing": "󰔟"
    },
    "tooltip": true,
    "on-click-right": "omarchy-voxtype-config",
    "on-click": "omarchy-voxtype-model"
  },
  "tray": {
    "icon-size": __WAYBAR_SYSTEM_ICON_SIZE_PX__,
    "spacing": __WAYBAR_TRAY_SPACING_PX__
  }
}
TOKENS

for waybar_config in \
  "${ROOT_DIR}/waybar-theme/config.jsonc"; do
  sed -i \
    -e "s|__WAYBAR_HEIGHT_PX__|${WAYBAR_HEIGHT_PX}|g" \
    -e "s|__WAYBAR_SYSTEM_ICON_SIZE_PX__|${WAYBAR_SYSTEM_ICON_SIZE_PX}|g" \
    -e "s|__WAYBAR_TRAY_SPACING_PX__|${WAYBAR_TRAY_SPACING_PX}|g" \
    "${waybar_config}"
done

cat > "${ROOT_DIR}/waybar-theme/style.css" <<TOKENS
/* AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh */
@import "../omarchy/current/theme/waybar.css";

.modules-left {
  margin-left: ${WAYBAR_LEFT_MARGIN_PX}px;
}

.modules-right {
  margin-right: ${WAYBAR_RIGHT_MARGIN_PX}px;
}

#custom-update {
  margin-left: 4px;
}

#custom-voxtype,
#custom-screenrecording-indicator,
#custom-idle-indicator,
#custom-notification-silencing-indicator {
  margin-left: 2px;
}

#custom-expand-icon {
  margin-right: 0;
}

#tray {
  margin-right: ${WAYBAR_GROUP_GAP_PX}px;
}
TOKENS

cat > "${ROOT_DIR}/qbar.css" <<TOKENS
/* AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh */
/* Future-facing qbar theme contract. This file is not applied automatically by this theme. */
:root {
  --qbar-font-family: ${UI_FONT_STACK};
  --qbar-font-size: ${WAYBAR_THEME_FONT_SIZE_PX}px;
  --qbar-font-weight: 600;
  --qbar-text: ${FOREGROUND};
  --qbar-text-strong: ${FOREGROUND_BRIGHT};
  --qbar-muted: ${SUBTLE};
  --qbar-border: ${WAYBAR_BORDER};
  --qbar-background: transparent;
  --qbar-hover: rgba(${FOREGROUND_RGB}, ${WAYBAR_HOVER_ALPHA});
  --qbar-surface: ${SURFACE};
  --qbar-overlay: ${OVERLAY};
  --qbar-accent: ${BLUE};
  --qbar-accent-alt: ${CYAN};
  --qbar-ok: ${GREEN};
  --qbar-warn: ${YELLOW};
  --qbar-critical: ${RED};
  --qbar-radius: ${WAYBAR_QBAR_PILL_RADIUS_PX}px;
  --qbar-icon-size: ${WAYBAR_QBAR_ICON_SIZE_PX}px;
  --qbar-gap: 4px;
  --qbar-padding-left: ${WAYBAR_QBAR_PADDING_LEFT_PX}px;
  --qbar-padding-right: ${WAYBAR_QBAR_PADDING_RIGHT_PX}px;
  --qbar-margin: ${WAYBAR_QBAR_MARGIN};
}

#custom-qbar-claude,
#custom-qbar-codex,
#custom-qbar-antigravity,
#custom-qbar-amp {
  min-height: ${WAYBAR_HEIGHT_PX}px;
  margin: var(--qbar-margin);
  padding: 0 var(--qbar-padding-right) 0 var(--qbar-padding-left);
  border: 1px solid transparent;
  border-radius: var(--qbar-radius);
  background: var(--qbar-background);
  background-position: 4px center;
  background-repeat: no-repeat;
  background-size: var(--qbar-icon-size) var(--qbar-icon-size);
  color: var(--qbar-text);
  font-family: var(--qbar-font-family);
  font-size: var(--qbar-font-size);
  font-weight: var(--qbar-font-weight);
  transition: background-color 120ms ease, color 120ms ease;
}

#custom-qbar-claude:hover,
#custom-qbar-codex:hover,
#custom-qbar-antigravity:hover,
#custom-qbar-amp:hover {
  background: var(--qbar-hover);
  color: var(--qbar-text-strong);
}

#custom-qbar-claude.ok,
#custom-qbar-codex.ok,
#custom-qbar-antigravity.ok,
#custom-qbar-amp.ok {
  color: var(--qbar-ok);
}

#custom-qbar-claude.low,
#custom-qbar-codex.low,
#custom-qbar-antigravity.low,
#custom-qbar-amp.low,
#custom-qbar-claude.warn,
#custom-qbar-codex.warn,
#custom-qbar-antigravity.warn,
#custom-qbar-amp.warn {
  color: var(--qbar-warn);
}

#custom-qbar-claude.critical,
#custom-qbar-codex.critical,
#custom-qbar-antigravity.critical,
#custom-qbar-amp.critical,
#custom-qbar-claude.disconnected,
#custom-qbar-codex.disconnected,
#custom-qbar-antigravity.disconnected,
#custom-qbar-amp.disconnected {
  color: var(--qbar-critical);
}
TOKENS

cat > "${ROOT_DIR}/walker.css" <<TOKENS
/* AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh */
@define-color selected-text ${WALKER_SELECTED_TEXT};
@define-color text-strong ${WALKER_TEXT_STRONG};
@define-color text ${WALKER_TEXT};
@define-color hint ${WALKER_HINT_TEXT};
@define-color base ${WALKER_BASE_BG};
@define-color border ${WALKER_BORDER};
@define-color selected-border ${WALKER_SELECTED_BORDER};
@define-color foreground ${WALKER_TEXT};
@define-color background ${WALKER_SEARCH_BG};
@define-color input ${WALKER_INPUT_BG};
@define-color hover-box ${WALKER_HOVER_BG};
@define-color selected-box ${WALKER_SELECTED_BG};

window {
  background-color: transparent;
  border: none;
  border-width: 0;
  border-color: @border;
  padding: 0;
  box-shadow: none;
}

.search-container {
  background: transparent;
  border: none;
  border-radius: ${WALKER_RADIUS}px;
  padding: 0;
}

window .box-wrapper {
  border-radius: ${WALKER_RADIUS}px;
  border: 1px solid @border;
  padding: ${WALKER_WRAPPER_PADDING_Y}px ${WALKER_WRAPPER_PADDING_X}px;
  background: @base;
  background-color: @base;
  box-shadow: none;
}

window .search-container {
  background: transparent;
  background-color: transparent;
}

#entry entry,
.input {
  font-family: ${UI_FONT_STACK};
  font-size: 15px;
  font-weight: 600;
  background-color: @input;
  color: @text-strong;
  border-radius: ${WALKER_RADIUS}px;
  padding: ${WALKER_INPUT_PADDING_Y}px ${WALKER_ALIGNED_PADDING_X}px;
  border: 1px solid @border;
  background-image: none;
  box-shadow: none;
  outline: none;
}

#entry * {
  font-family: ${UI_FONT_STACK};
  background-color: @input;
  background-image: none;
  box-shadow: none;
}

#entry entry placeholder,
.input placeholder,
window .placeholder {
  color: @hint;
}

#entry:selected {
  color: @text-strong;
}

child {
  padding: ${WALKER_ITEM_GAP_Y}px ${WALKER_ITEM_GAP_X}px;
}

child .item-box {
  border-radius: ${WALKER_RADIUS}px;
  border: 1px solid transparent;
  background: @base;
}

child:hover .item-box {
  background-image: none;
  border: 1px solid @border;
  background-color: @hover-box;
  border-radius: ${WALKER_RADIUS}px;
  box-shadow: none;
}

child:selected .item-box {
  background-image: none;
  border: 1px solid @selected-border;
  background-color: @selected-box;
  border-radius: ${WALKER_RADIUS}px;
  box-shadow: none;
}

child .item-text {
  font-family: ${UI_FONT_STACK};
  font-size: 14px;
  font-weight: 600;
  color: @foreground;
}

window .item-box {
  padding: 0 ${WALKER_ALIGNED_PADDING_X}px;
}

window .item-text-box {
  font-family: ${UI_FONT_STACK};
  padding: ${WALKER_ITEM_TEXT_PADDING_Y}px 0;
}

window .item-image {
  margin-right: ${WALKER_ITEM_IMAGE_GAP}px;
  -gtk-icon-transform: scale(0.85);
}

child:hover .item-text {
  color: @text-strong;
}

child:selected .item-text {
  color: @selected-text;
}

window .current,
window .keybind-hints {
  font-family: ${UI_FONT_STACK};
  color: @hint;
}

window .box-wrapper #entry,
window .box-wrapper #entry * {
  background: @input;
  background-color: @input;
  background-image: none;
  box-shadow: none;
  outline: none;
}
TOKENS

chmod +x "${ROOT_DIR}/scripts/build-theme.sh"

echo "Theme files generated from theme.tokens.sh"
