#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

# shellcheck source=../theme.tokens.sh
source "${ROOT_DIR}/theme.tokens.sh"

hex_nohash() {
  printf '%s' "${1#\#}"
}

hex_to_rgb() {
  local hex
  hex="$(hex_nohash "$1")"
  printf '%d, %d, %d' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

BACKGROUND_NOHASH="$(hex_nohash "${BACKGROUND}")"
SURFACE_NOHASH="$(hex_nohash "${SURFACE}")"
SELECTION_NOHASH="$(hex_nohash "${SELECTION}")"
FOREGROUND_NOHASH="$(hex_nohash "${FOREGROUND}")"
COMMENT_NOHASH="$(hex_nohash "${COMMENT}")"
RED_NOHASH="$(hex_nohash "${RED}")"
GREEN_NOHASH="$(hex_nohash "${GREEN}")"
YELLOW_NOHASH="$(hex_nohash "${YELLOW}")"
BLUE_NOHASH="$(hex_nohash "${BLUE}")"
MAGENTA_NOHASH="$(hex_nohash "${MAGENTA}")"
CYAN_NOHASH="$(hex_nohash "${CYAN}")"
ORANGE_NOHASH="$(hex_nohash "${ORANGE}")"
BRIGHT_WHITE_NOHASH="$(hex_nohash "${BRIGHT_WHITE}")"
BRIGHT_BLUE_NOHASH="$(hex_nohash "${BRIGHT_BLUE}")"
BRIGHT_MAGENTA_NOHASH="$(hex_nohash "${BRIGHT_MAGENTA}")"
BRIGHT_CYAN_NOHASH="$(hex_nohash "${BRIGHT_CYAN}")"

BLUE_RGB="$(hex_to_rgb "${BLUE}")"
BACKGROUND_RGB="$(hex_to_rgb "${BACKGROUND}")"
FOREGROUND_RGB="$(hex_to_rgb "${FOREGROUND}")"
SURFACE_RGB="$(hex_to_rgb "${SURFACE}")"
GREEN_RGB="$(hex_to_rgb "${GREEN}")"
YELLOW_RGB="$(hex_to_rgb "${YELLOW}")"
RED_RGB="$(hex_to_rgb "${RED}")"
SELECTION_RGB="$(hex_to_rgb "${SELECTION}")"
COMMENT_RGB="$(hex_to_rgb "${COMMENT}")"
BRIGHT_WHITE_RGB="$(hex_to_rgb "${BRIGHT_WHITE}")"

cat > "${ROOT_DIR}/colors.toml" <<TOKENS
# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
accent = "${BLUE}"
cursor = "${FOREGROUND}"
foreground = "${FOREGROUND}"
background = "${BACKGROUND}"
selection_foreground = "${FOREGROUND}"
selection_background = "${SELECTION}"

color0 = "${BACKGROUND}"
color1 = "${RED}"
color2 = "${GREEN}"
color3 = "${YELLOW}"
color4 = "${BLUE}"
color5 = "${MAGENTA}"
color6 = "${CYAN}"
color7 = "${FOREGROUND}"
color8 = "${COMMENT}"
color9 = "${RED}"
color10 = "${GREEN}"
color11 = "${YELLOW}"
color12 = "${BLUE}"
color13 = "${MAGENTA}"
color14 = "${CYAN}"
color15 = "${BRIGHT_WHITE}"
TOKENS

cat > "${ROOT_DIR}/alacritty.toml" <<TOKENS
# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
[colors.primary]
background = "${BACKGROUND}"
foreground = "${FOREGROUND}"
bright_foreground = "${BRIGHT_WHITE}"

[colors.cursor]
text = "${BACKGROUND}"
cursor = "${FOREGROUND}"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.selection]
text = "CellForeground"
background = "${SELECTION}"

[colors.normal]
black = "${BACKGROUND}"
red = "${RED}"
green = "${GREEN}"
yellow = "${YELLOW}"
blue = "${BLUE}"
magenta = "${MAGENTA}"
cyan = "${CYAN}"
white = "${FOREGROUND}"

[colors.bright]
black = "${COMMENT}"
red = "${RED}"
green = "${GREEN}"
yellow = "${YELLOW}"
blue = "${BLUE}"
magenta = "${MAGENTA}"
cyan = "${CYAN}"
white = "${BRIGHT_WHITE}"

[colors.search.matches]
foreground = "${SELECTION}"
background = "${GREEN}"

[colors.search.focused_match]
foreground = "${SELECTION}"
background = "${YELLOW}"

[colors.footer_bar]
background = "${BACKGROUND}"
foreground = "${FOREGROUND}"

[colors.hints.start]
foreground = "${BACKGROUND}"
background = "${YELLOW}"

[colors.hints.end]
foreground = "${YELLOW}"
background = "${BACKGROUND}"
TOKENS

cat > "${ROOT_DIR}/kitty.conf" <<TOKENS
# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
background            ${BACKGROUND}
foreground            ${FOREGROUND}

color0  ${BACKGROUND}
color1  ${RED}
color2  ${GREEN}
color3  ${YELLOW}
color4  ${BLUE}
color5  ${MAGENTA}
color6  ${CYAN}
color7  ${FOREGROUND}
color8  ${COMMENT}
color9  ${RED}
color10 ${GREEN}
color11 ${YELLOW}
color12 ${BLUE}
color13 ${MAGENTA}
color14 ${CYAN}
color15 ${BRIGHT_WHITE}
TOKENS

cat > "${ROOT_DIR}/ghostty.conf" <<TOKENS
# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
background = ${BACKGROUND}
background-opacity = ${TERMINAL_BACKGROUND_OPACITY}
foreground = ${FOREGROUND}
cursor-color = ${FOREGROUND}
cursor-text = ${BACKGROUND}

selection-background = ${SELECTION}
selection-foreground = ${FOREGROUND}

palette = 0=${BACKGROUND}
palette = 1=${RED}
palette = 2=${GREEN}
palette = 3=${YELLOW}
palette = 4=${BLUE}
palette = 5=${MAGENTA}
palette = 6=${CYAN}
palette = 7=${FOREGROUND}

palette = 8=${COMMENT}
palette = 9=${RED}
palette = 10=${GREEN}
palette = 11=${YELLOW}
palette = 12=${BLUE}
palette = 13=${MAGENTA}
palette = 14=${CYAN}
palette = 15=${BRIGHT_WHITE}
TOKENS

cat > "${ROOT_DIR}/colors.fish" <<TOKENS
# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
set -U background '${BACKGROUND}'
set -U foreground '${FOREGROUND}'
set -U cursor '${FOREGROUND}'
set -U color0 '${BACKGROUND}'
set -U color1 '${RED}'
set -U color2 '${GREEN}'
set -U color3 '${YELLOW}'
set -U color4 '${BLUE}'
set -U color5 '${MAGENTA}'
set -U color6 '${CYAN}'
set -U color7 '${FOREGROUND}'
set -U color8 '${COMMENT}'
set -U color9 '${RED}'
set -U color10 '${GREEN}'
set -U color11 '${YELLOW}'
set -U color12 '${BLUE}'
set -U color13 '${MAGENTA}'
set -U color14 '${CYAN}'
set -U color15 '${BRIGHT_WHITE}'

set -U fish_color_normal normal
set -U fish_color_command green
set -U fish_color_param cyan
set -U fish_pager_color_completion
set -U fish_pager_color_description \$fish_color_quote yellow
set -U fish_pager_color_progress brwhite --background=cyan
set -U fish_color_history_current --bold
TOKENS

cat > "${ROOT_DIR}/fzf.fish" <<TOKENS
# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
set -l color00 '${BACKGROUND}'
set -l color01 '${RED}'
set -l color02 '${GREEN}'
set -l color03 '${YELLOW}'
set -l color04 '${BLUE}'
set -l color05 '${MAGENTA}'
set -l color06 '${CYAN}'
set -l color07 '${FOREGROUND}'
set -l color08 '${COMMENT}'
set -l color09 '${RED}'
set -l color0A '${GREEN}'
set -l color0B '${YELLOW}'
set -l color0C '${BLUE}'
set -l color0D '${MAGENTA}'
set -l color0E '${CYAN}'
set -l color0F '${BRIGHT_WHITE}'

set -l FZF_NON_COLOR_OPTS

for arg in (echo \$FZF_DEFAULT_OPTS | tr " " "\\n")
    if not string match -q -- "--color*" \$arg
        set -a FZF_NON_COLOR_OPTS \$arg
    end
end

set -Ux FZF_DEFAULT_OPTS "\$FZF_NON_COLOR_OPTS"" --color=bg+:\$color00,bg:\$color00,spinner:\$color0E,hl:\$color0D"" --color=fg:\$color07,header:\$color0D,info:\$color0A,pointer:\$color0E"" --color=marker:\$color0E,fg+:\$color06,prompt:\$color0A,hl+:\$color0D"
TOKENS

cat > "${ROOT_DIR}/waybar.css" <<TOKENS
/* AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh */
@define-color background-darker ${SURFACE};
@define-color background ${BACKGROUND};
@define-color selection ${SELECTION};
@define-color foreground ${FOREGROUND};
@define-color comment ${COMMENT};
@define-color cyan ${CYAN};
@define-color green ${GREEN};
@define-color orange ${ORANGE};
@define-color pink ${MAGENTA};
@define-color purple ${BLUE};
@define-color red ${RED};
@define-color yellow ${YELLOW};

* {
  border: none;
  border-radius: 0;
  box-shadow: none;
  font-family: Iosevka;
  font-size: 11pt;
  min-height: 0;
}

window#waybar {
  background: @background-darker;
  color: @foreground;
}

.modules-left,
.modules-center,
.modules-right {
  background: @background;
}

#workspaces {
  background: @background;
}

#workspaces button {
  background: @background;
  color: @foreground;
}

#workspaces button.urgent {
  background: @red;
  color: @background;
}

#clock {
  padding: 0 4px;
  background: @background;
}
TOKENS

cat > "${ROOT_DIR}/waybar-theme/style.css" <<TOKENS
/* AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh */
@import "../waybar.css";

@define-color background ${BACKGROUND};
@define-color base ${BACKGROUND};
@define-color surface ${SURFACE};
@define-color overlay ${OVERLAY};
@define-color muted ${COMMENT};
@define-color subtle ${SUBTLE};
@define-color text ${FOREGROUND};
@define-color love ${MAGENTA};
@define-color gold ${YELLOW};
@define-color rose ${ORANGE};
@define-color pine ${CYAN};
@define-color foam ${GREEN};
@define-color iris ${BLUE};
@define-color highlight_low ${OVERLAY};
@define-color highlight_med ${SELECTION};
@define-color highlight_high ${COMMENT};

* {
  font-family: "JetBrainsMono Nerd Font Propo";
  font-size: 12px;
  font-weight: bold;
  min-height: 0;
}

window#waybar {
  background-color: @background;
  transition-property: background-color;
  transition-duration: 0.5s;
}

window#waybar.empty #window {
  background: @background;
  border: none;
  border-radius: 0;
  color: @text;
  padding: 0;
  margin: 0;
}

#waybar.empty .modules-center {
  opacity: 0;
}

tooltip {
  opacity: 1;
  padding: 4px;
  background-color: @surface;
  border: 1px solid @highlight_med;
  border-radius: 4px;
  font-size: 12px;
}

tooltip label {
  color: @text;
  font-weight: normal;
}

#workspaces {
  border-radius: 2px;
  margin: 6px 3px;
}

#workspaces button {
  padding: 0 2px;
  margin: 0 3px 0 0;
  border-radius: 2px;
  background-color: @surface;
  color: @text;
}

#workspaces button.active {
  background-color: @gold;
  color: @base;
}

#workspaces button:hover {
  background-color: @highlight_med;
  color: @gold;
}

#tray,
#window,
#mpris,
#cpu,
#clock,
#battery,
#network,
#memory,
#backlight,
#bluetooth,
#pulseaudio,
#custom-weather,
#custom-update,
#idle_inhibitor,
#custom-omarchy,
#custom-screenrecording-indicator,
#custom-updatespacman {
  min-width: 14px;
  margin: 6px 3px;
  padding: 4px 8px;
  border-radius: 2px;
}

#clock:hover,
#tray:hover,
#custom-expand-icon:hover,
#cpu:hover,
#memory:hover,
#temperature:hover,
#battery:hover,
#bluetooth:hover,
#backlight:hover,
#custom-omarchy:hover,
#custom-weather:hover,
#custom-update:hover,
#idle_inhibitor:hover,
#custom-screenrecording-indicator:hover,
#custom-updatespacman:hover,
#network:hover,
#pulseaudio:hover {
  border-radius: 2px;
  background-color: @highlight_high;
  color: @text;
}

#window {
  background-color: @highlight_low;
  color: @gold;
}

#custom-omarchy {
  background-color: @surface;
  color: @gold;
}

#custom-update,
#custom-updatespacman {
  background-color: @pine;
  color: @base;
}

#clock {
  background-color: @surface;
  color: @gold;
}

#idle_inhibitor,
#idle_inhibitor.deactivated {
  background-color: @muted;
  color: @base;
}

#idle_inhibitor.activated {
  background-color: @foam;
  color: @base;
}

#custom-weather {
  background-color: @overlay;
  color: @foam;
}

#tray {
  background-color: @overlay;
  color: @gold;
}

#battery {
  background-color: @foam;
  color: @base;
}

#cpu {
  background-color: @gold;
  color: @base;
}

#memory {
  background-color: @pine;
  color: @base;
}

#network {
  background-color: @iris;
  color: @base;
}

#pulseaudio {
  background-color: @love;
  color: @base;
}

#backlight {
  background-color: @rose;
  color: @base;
}

#bluetooth {
  background-color: @foam;
  color: @base;
}

#mpris {
  background-color: @iris;
  color: @foam;
  animation-name: blink;
  animation-duration: 3s;
  animation-timing-function: linear;
  animation-iteration-count: infinite;
  animation-direction: alternate;
}

#mpris.paused {
  color: @text;
}

#tray > .passive {
  -gtk-icon-effect: dim;
  color: @gold;
}

#tray > .needs-attention {
  -gtk-icon-effect: highlight;
  background-color: @overlay;
  color: @gold;
}

#tray * {
  color: @gold;
}

.hidden {
  opacity: 0;
}

#cpu.critical,
#memory.critical,
#battery.warning,
#battery.critical,
#battery.urgent {
  background-color: @love;
  color: @base;
}

#custom-screenrecording-indicator {
  animation-timing-function: linear;
  animation-iteration-count: infinite;
  animation-direction: alternate;
  color: @surface;
}

#custom-screenrecording-indicator.active {
  color: @love;
  animation-name: blink-recording;
  animation-duration: 0.5s;
}

@keyframes blink-recording {
  to {
    color: @surface;
  }
}

@keyframes blink {
  to {
    color: @text;
  }
}
TOKENS

cat > "${ROOT_DIR}/walker.css" <<TOKENS
/* AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh */
@define-color selected-text ${CYAN};
@define-color text ${COMMENT};
@define-color base ${BACKGROUND};
@define-color border ${BLUE};
@define-color foreground ${FOREGROUND};
@define-color background ${SELECTION};
@define-color input ${SELECTION};
@define-color selected-box ${SELECTION};
@define-color selected-border ${COMMENT};

window {
  background-color: @base;
  border: none;
  border-width: 0;
  border-color: @border;
  padding: 0;
  box-shadow: none;
}

.search-container {
  background: @background;
  border: none;
  border-radius: 12px;
  padding: 12px 16px;
}

window .box-wrapper {
  border-radius: 0;
  border: 2px solid @border;
  padding: 18px 22px;
  background: @base;
}

#entry entry,
.input {
  background-color: @input;
  color: @text;
  border-radius: 2px;
  padding: 12px 16px;
  border: none;
  background-image: none;
  box-shadow: none;
  outline: none;
}

#entry * {
  background-color: @base;
  background-image: none;
  box-shadow: none;
}

#entry:selected {
  color: @foreground;
}

child {
  padding: 2px 6px;
}

child .item-box {
  border-radius: 10px;
  background: @base;
}

child:hover .item-box,
child:selected .item-box {
  background-image: none;
  border: 2px solid @selected-border;
  background-color: @selected-box;
  border-radius: 0;
  box-shadow: none;
}

child:hover .item-text,
child:selected .item-text {
  color: @foreground;
}

window .box-wrapper #entry,
window .box-wrapper #entry * {
  background: @input;
  background-color: @input;
  background-image: none;
  box-shadow: none;
  border: none;
  outline: none;
}
TOKENS

cat > "${ROOT_DIR}/gtk.css" <<TOKENS
/* AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh */

@define-color background ${BACKGROUND};
@define-color foreground ${FOREGROUND};
@define-color black ${BACKGROUND};
@define-color red ${RED};
@define-color green ${GREEN};
@define-color yellow ${YELLOW};
@define-color blue ${BLUE};
@define-color magenta ${MAGENTA};
@define-color cyan ${CYAN};
@define-color white ${FOREGROUND};
@define-color bright_black ${COMMENT};
@define-color bright_red ${BRIGHT_RED};
@define-color bright_green ${BRIGHT_GREEN};
@define-color bright_yellow ${BRIGHT_YELLOW};
@define-color bright_blue ${BRIGHT_BLUE};
@define-color bright_magenta ${BRIGHT_MAGENTA};
@define-color bright_cyan ${BRIGHT_CYAN};
@define-color bright_white ${BRIGHT_WHITE};

@define-color accent_bg_color @blue;
@define-color accent_fg_color @background;
@define-color accent_color @cyan;

@define-color window_bg_color @background;
@define-color window_fg_color @foreground;
@define-color view_bg_color @black;
@define-color view_fg_color @foreground;
@define-color sidebar_bg_color @black;
@define-color sidebar_fg_color @foreground;
@define-color sidebar_backdrop_color @black;
@define-color sidebar_shade_color @black;
@define-color headerbar_bg_color @background;
@define-color headerbar_fg_color @foreground;
@define-color headerbar_backdrop_color @black;
@define-color headerbar_shade_color @black;
@define-color card_bg_color @background;
@define-color card_fg_color @foreground;
@define-color popover_bg_color @black;
@define-color popover_fg_color @foreground;
@define-color destructive_bg_color @red;
@define-color destructive_fg_color @background;
@define-color success_bg_color @green;
@define-color success_fg_color @background;
@define-color warning_bg_color @yellow;
@define-color warning_fg_color @background;
@define-color error_bg_color @red;
@define-color error_fg_color @background;
@define-color dialog_bg_color @background;
@define-color dialog_fg_color @foreground;

@define-color borders alpha(@foreground, 0.1);

@define-color theme_fg_color @foreground;
@define-color theme_text_color @foreground;
@define-color theme_bg_color @background;
@define-color theme_base_color @black;
@define-color theme_selected_bg_color @blue;
@define-color theme_selected_fg_color @background;

messagedialog,
alertdialog.background,
filechooser,
popover,
toast,
window {
  background-color: @background;
  color: @foreground;
}

messagedialog label,
alertdialog label {
  color: @dialog_fg_color;
}

messagedialog button {
  background-color: @black;
  color: @foreground;
  border: 1px solid @bright_black;
  padding: 10px;
}

messagedialog button:hover {
  background-color: @blue;
}

banner revealer widget {
  background: @bright_black;
  padding: 5px;
  color: @foreground;
}

alertdialog .titlebar {
  background-color: @headerbar_bg_color;
  color: @headerbar_fg_color;
}

filechooser .dialog-action-box {
  border-top: 1px solid @bright_black;
}

filechooser .dialog-action-box:backdrop {
  border-top-color: @black;
}

filechooser #pathbarbox {
  border-bottom: 1px solid @bright_black;
}

filechooserbutton:drop(active) {
  box-shadow: none;
  border-color: transparent;
}

toast button.circular.flat.image-button:hover {
  color: @background;
  background-color: @red;
}
TOKENS

cat > "${ROOT_DIR}/steam.css" <<TOKENS
/* AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh */
:root {
  --adw-accent-bg-rgb: ${BLUE_RGB} !important;
  --adw-accent-fg-rgb: ${BACKGROUND_RGB} !important;
  --adw-accent-rgb: ${BLUE_RGB} !important;

  --adw-destructive-bg-rgb: ${RED_RGB} !important;
  --adw-destructive-fg-rgb: ${FOREGROUND_RGB} !important;
  --adw-destructive-rgb: ${RED_RGB} !important;

  --adw-success-bg-rgb: ${GREEN_RGB} !important;
  --adw-success-rgb: ${GREEN_RGB} !important;

  --adw-warning-bg-rgb: ${YELLOW_RGB} !important;
  --adw-warning-rgb: ${YELLOW_RGB} !important;

  --adw-error-bg-rgb: ${RED_RGB} !important;
  --adw-error-rgb: ${RED_RGB} !important;

  --adw-window-bg-rgb: ${BACKGROUND_RGB} !important;
  --adw-window-fg-rgb: ${FOREGROUND_RGB} !important;

  --adw-view-bg-rgb: ${SURFACE_RGB} !important;
  --adw-view-fg-rgb: ${FOREGROUND_RGB} !important;

  --adw-headerbar-bg-rgb: ${BACKGROUND_RGB} !important;
  --adw-headerbar-fg-rgb: ${FOREGROUND_RGB} !important;
  --adw-headerbar-border-rgb: ${COMMENT_RGB} !important;
  --adw-headerbar-backdrop-rgb: ${SURFACE_RGB} !important;
  --adw-headerbar-shade-rgb: 0, 0, 0 !important;
  --adw-headerbar-shade-a: 0.36 !important;

  --adw-sidebar-bg-rgb: ${BACKGROUND_RGB} !important;
  --adw-sidebar-fg-rgb: ${FOREGROUND_RGB} !important;
  --adw-sidebar-backdrop-rgb: ${COMMENT_RGB} !important;
  --adw-sidebar-shade-rgb: 0, 0, 0 !important;
  --adw-sidebar-shade-a: 0.36 !important;

  --adw-card-bg-rgb: ${BRIGHT_WHITE_RGB} !important;
  --adw-card-bg-a: 0.08 !important;
  --adw-card-fg-rgb: ${BRIGHT_WHITE_RGB} !important;

  --adw-dialog-bg-rgb: ${BACKGROUND_RGB} !important;
  --adw-dialog-fg-rgb: ${FOREGROUND_RGB} !important;

  --adw-popover-bg-rgb: ${BACKGROUND_RGB} !important;
  --adw-popover-fg-rgb: ${FOREGROUND_RGB} !important;

  --adw-thumbnail-bg-rgb: ${BACKGROUND_RGB} !important;
}
TOKENS

cat > "${ROOT_DIR}/swayosd.css" <<TOKENS
/* AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh */
@define-color background-color ${BACKGROUND};
@define-color border-color ${SELECTION};
@define-color label ${COMMENT};
@define-color image ${COMMENT};
@define-color progress ${GREEN};
TOKENS

cat > "${ROOT_DIR}/btop.theme" <<TOKENS
# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh

theme[main_bg]="${BACKGROUND}"
theme[main_fg]="${FOREGROUND}"
theme[title]="${BLUE}"
theme[hi_fg]="${YELLOW}"
theme[selected_bg]="${SELECTION}"
theme[selected_fg]="${GREEN}"
theme[inactive_fg]="${COMMENT}"
theme[graph_text]="${CYAN}"
theme[meter_bg]="${SELECTION}"
theme[proc_misc]="${MAGENTA}"
theme[cpu_box]="${RED}"
theme[mem_box]="${GREEN}"
theme[net_box]="${CYAN}"
theme[proc_box]="${YELLOW}"
theme[div_line]="${COMMENT}"

theme[temp_start]="${RED}"
theme[temp_mid]="${YELLOW}"
theme[temp_end]="${GREEN}"

theme[cpu_start]="${YELLOW}"
theme[cpu_mid]="${GREEN}"
theme[cpu_end]="${CYAN}"

theme[free_start]="${CYAN}"
theme[free_mid]="${CYAN}"
theme[free_end]="${CYAN}"

theme[cached_start]="${BLUE}"
theme[cached_mid]="${BLUE}"
theme[cached_end]="${BLUE}"

theme[available_start]="${GREEN}"
theme[available_mid]="${GREEN}"
theme[available_end]="${GREEN}"

theme[used_start]="${RED}"
theme[used_mid]="${RED}"
theme[used_end]="${RED}"

theme[download_start]="${GREEN}"
theme[download_mid]="${CYAN}"
theme[download_end]="${CYAN}"

theme[upload_start]="${YELLOW}"
theme[upload_mid]="${RED}"
theme[upload_end]="${RED}"

theme[process_start]="${GREEN}"
theme[process_mid]="${CYAN}"
theme[process_end]="${CYAN}"
TOKENS

cat > "${ROOT_DIR}/cava_theme" <<TOKENS
# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
[color]
gradient = 1
gradient_count = 8
gradient_color_1 = '${CYAN}'
gradient_color_2 = '${BLUE}'
gradient_color_3 = '${BRIGHT_BLUE}'
gradient_color_4 = '${MAGENTA}'
gradient_color_5 = '${BRIGHT_MAGENTA}'
gradient_color_6 = '${BRIGHT_CYAN}'
gradient_color_7 = '${BRIGHT_MAGENTA}'
gradient_color_8 = '${CYAN}'
TOKENS

cat > "${ROOT_DIR}/hyprlock.conf" <<TOKENS
# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
\$check_color = rgba(${GREEN_RGB},1.0)

\$color       = rgba(${BACKGROUND_RGB},1.0)
\$inner_color = rgba(${BACKGROUND_RGB},1.0)
\$outer_color = rgba(${BLUE_RGB},1.0)
\$font_color  = rgba(${FOREGROUND_RGB},1.0)
TOKENS

cat > "${ROOT_DIR}/hyprland.conf" <<TOKENS
# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh

general {
    col.active_border = rgba(${BLUE_NOHASH}ee) rgba(${CYAN_NOHASH}ee) 65deg
    col.inactive_border = rgba(${SELECTION_NOHASH}ff)
}

decoration {
    rounding = 0

    shadow {
        enabled = true
        range = 12
        render_power = 6
        offset = 0 0
        ignore_window = false
        color = rgba(${BLUE_NOHASH}ee)
        color_inactive = rgba(${COMMENT_NOHASH}33)
    }
}

windowrule {
  name = windowrule-1
  opacity = ${WINDOW_OPACITY} ${WINDOW_OPACITY} # Window opacity control: keep both values at 1.0 for solid windows.
  match:class = .*
}

windowrule {
  name = windowrule-2
  no_dim = on
  opacity = ${WINDOW_OPACITY} override ${WINDOW_OPACITY} override # Window opacity control: override app defaults to fully opaque.
  match:class = (^brave-youtube\.com__-Default$)
}

windowrule {
  name = windowrule-gimp
  tag = -default-opacity
  no_dim = on
  opacity = ${WINDOW_OPACITY} override ${WINDOW_OPACITY} override ${WINDOW_OPACITY} override # Window opacity control: force GIMP solid.
  match:class = ^gimp$
}

windowrule {
  name = windowrule-3
  no_dim = on
  opacity = ${WINDOW_OPACITY} override ${WINDOW_OPACITY} override # Window opacity control: force Netflix webapp solid.
  match:class = (^brave-www\.netflix\.com__browse-Default$)
}
TOKENS

cat > "${ROOT_DIR}/vencord.theme.css" <<TOKENS
/**
 * AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
 * @name One Dark Pro Flat | based on midnight by refact0r
 * @description A dark One Dark Pro theme for Discord
 * @author One Dark Pro Adaptation
 * @version 3.4
 */

@import url('https://refact0r.github.io/midnight-discord/build/midnight.css');

body {
    --font: 'figtree';
    --code-font: '';
    font-weight: 400;
    --gap: 12px;
    --divider-thickness: 4px;
    --border-thickness: 2px;
    --animations: on;
    --list-item-transition: 0.2s ease;
    --dms-icon-svg-transition: 0.4s ease;
    --border-hover-transition: 0.2s ease;
    --top-bar-height: var(--gap);
    --top-bar-button-position: titlebar;
    --top-bar-title-position: off;
    --subtle-top-bar-title: off;
    --custom-window-controls: on;
    --window-control-size: 14px;
    --custom-dms-icon: off;
    --dms-icon-svg-url: url('');
    --dms-icon-svg-size: 90%;
    --dms-icon-color-before: var(--icon-secondary);
    --dms-icon-color-after: var(--white);
    --custom-dms-background: off;
    --dms-background-image-url: url('');
    --dms-background-image-size: cover;
    --dms-background-color: linear-gradient(70deg, var(--blue-2), var(--purple-2), var(--red-2));
    --background-image: off;
    --background-image-url: url('');
    --transparency-tweaks: off;
    --remove-bg-layer: off;
    --panel-blur: off;
    --blur-amount: 12px;
    --bg-floating: var(--bg-3);
    --custom-chatbar: aligned;
    --chatbar-height: 47px;
    --chatbar-padding: 8px;
    --small-user-panel: on;
}

:root {
    --colors: on;
    --text-0: ${BACKGROUND};
    --text-1: ${FOREGROUND};
    --text-2: ${CYAN};
    --text-3: ${FOREGROUND};
    --text-4: ${COMMENT};
    --text-5: ${COMMENT};
    --bg-1: ${BACKGROUND};
    --bg-2: ${BACKGROUND};
    --bg-3: ${BACKGROUND};
    --bg-4: ${BACKGROUND};
    --hover: ${SELECTION};
    --active: ${SELECTION};
    --active-2: ${SELECTION};
    --message-hover: ${SELECTION};
    --accent-1: ${BLUE};
    --accent-2: ${BLUE};
    --accent-3: ${BLUE};
    --accent-4: ${BLUE};
    --accent-5: ${BLUE};
    --accent-new: ${RED};
    --mention: linear-gradient(to right, color-mix(in hsl, ${BLUE}, transparent 90%) 40%, transparent);
    --mention-hover: linear-gradient(to right, color-mix(in hsl, ${BLUE}, transparent 95%) 40%, transparent);
    --reply: linear-gradient(to right, color-mix(in hsl, ${FOREGROUND}, transparent 90%) 40%, transparent);
    --reply-hover: linear-gradient(to right, color-mix(in hsl, ${FOREGROUND}, transparent 95%) 40%, transparent);
    --online: ${GREEN};
    --dnd: ${RED};
    --idle: ${YELLOW};
    --streaming: ${BLUE};
    --offline: ${COMMENT};
    --border-light: ${SELECTION};
    --border: ${SELECTION};
    --border-hover: ${BLUE};
    --button-border: ${SELECTION};
    --red: ${RED};
    --orange: ${ORANGE};
    --yellow: ${YELLOW};
    --green: ${GREEN};
    --cyan: ${CYAN};
    --purple: ${BLUE};
    --pink: ${MAGENTA};
}

*,
*::before,
*::after {
    border-radius: 0 !important;
}
TOKENS

cat > "${ROOT_DIR}/lazygit.yml" <<TOKENS
# AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
theme:
  activeBorderColor:
    - "${MAGENTA}"
    - bold
  inactiveBorderColor:
    - "${BLUE}"
  searchingActiveBorderColor:
    - "${CYAN}"
    - bold
  optionsTextColor:
    - "${COMMENT}"
  selectedLineBgColor:
    - "${COMMENT}"
  inactiveViewSelectedLineBgColor:
    - bold
  cherryPickedCommitFgColor:
    - "${COMMENT}"
  cherryPickedCommitBgColor:
    - "${CYAN}"
  markedBaseCommitFgColor:
    - "${CYAN}"
  markedBaseCommitBgColor:
    - "${YELLOW}"
  unstagedChangesColor:
    - "${RED}"
  defaultFgColor:
    - "${FOREGROUND}"
TOKENS

cat > "${ROOT_DIR}/neovim.lua" <<TOKENS
-- AUTO-GENERATED by scripts/build-theme.sh from theme.tokens.sh
return {
  {
    "olimorris/onedarkpro.nvim",
    priority = 1000,
    config = function()
      require("onedarkpro").setup({
        theme = "onedark",
        highlights = {
          LineNr = { fg = "${COMMENT}", bg = "bg" },
          TabLineFill = { bg = "bg" },
          TabLine = { bg = "bg" },
          TabLineSel = { bg = "${BACKGROUND}" },
        },
      })
      vim.cmd("colorscheme onedark")
    end,
  },
}
TOKENS

chmod +x "${ROOT_DIR}/scripts/build-theme.sh"

echo "Theme files generated from theme.tokens.sh"
